# Replace $0 with name entry 
SELECT ?name ?description ?TerritoryLocation ?TerritoryLocationLabel ?CountryLocation ?CountryLocationLabel ?inception ?SocialMediaFollowers ?coordinates WHERE {
  BIND(wd:$0 AS ?entity)
  OPTIONAL { ?entity rdfs:label ?name. filter (lang(?name) = "en")}
  OPTIONAL { ?entity schema:description ?description. filter (lang(?description) = "en")}
  OPTIONAL { ?entity wdt:P131 ?TerritoryLocation. }
  OPTIONAL { ?entity wdt:P17 ?CountryLocation. }
  OPTIONAL { ?entity wdt:P571 ?inception. }
  OPTIONAL { ?entity wdt:P8687 ?SocialMediaFollowers. }
  OPTIONAL { ?entity wdt:P625 ?coordinates. }
  SERVICE wikibase:label { bd:serviceParam wikibase:language "en". }
}