# Replace $0 with book entity id
SELECT ?name ?description ?authorLabel ?genreLabel ?published WHERE {
  BIND(wd:$0 AS ?entity)
  OPTIONAL { ?entity rdfs:label ?name. filter (lang(?name) = "en")}
  OPTIONAL { ?entity schema:description ?description. filter (lang(?description) = "en")}
  OPTIONAL { ?entity wdt:P50 ?author. }
  OPTIONAL { ?entity wdt:P136 ?genre. }
  OPTIONAL { ?entity wdt:P577 ?published. }
  SERVICE wikibase:label { bd:serviceParam wikibase:language "en". }
}
