# Replace $0 with name entry 
SELECT ?name ?description ?birthDate ?deathDate ?spouse ?spouseLabel ?nationality ?nationalityLabel ?occupation ?occupationLabel WHERE {
  BIND(wd:$0 AS ?entity)
  OPTIONAL { ?entity rdfs:label ?name. filter (lang(?name) = "en")}
  OPTIONAL { ?entity schema:description ?description. filter (lang(?description) = "en")}
  OPTIONAL { ?entity wdt:P569 ?birthDate. }
  OPTIONAL { ?entity wdt:P570 ?deathDate. }
  OPTIONAL { ?entity wdt:P26 ?spouse. }
  OPTIONAL { ?entity wdt:P27 ?nationality. }
  OPTIONAL { ?entity wdt:P106 ?occupation. }
  SERVICE wikibase:label { bd:serviceParam wikibase:language "en". }
}