name: Backend CI
on: push

jobs:
  lint-backend:
    name: 'Linting'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: pylint
        uses: cclauss/GitHub-Action-for-pylint@master
        with:
        # Installs Django and pylint-django, then runs pylint on all of the files in autoscheduler/
          args: pip install -r .github/lint-requirements.txt ; pylint know/know know/rdf --load-plugins pylint_django --rcfile=know/.pylintrc --django-settings-module=know.settings

  test-backend:
    name: 'Testing'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: docker-build
        run: docker-compose up --build --abort-on-container-exit tests
