name: Danger
on: 
  pull_request:
    # By default, the pull_request event only triggers on [opened, synchronize, reopened]
    types: [opened, synchronize, reoponed, assigned, unassigned, labeled, unlabeled]

jobs:
    danger:
      name: Danger JS
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v1
        - name: Danger
          uses: danger/danger-js@9.1.6
          with:
            args: "--dangerfile ./.github/dangerfile.ts"
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}